### PR TITLE
[GH-311] Fix issues: Not able to create meeting in threads view and by clicking "Create New Metting" button in a channel

### LINKED ISSUE #311: Create new meeting causes an issue of generating multiple similar custom posts.
If a user initiates a new meeting, and once the meeting is going on, that user again tries to start a new meeting, then he will receive a custom post to create a new meeting or join an existing one. On clicking on create new meeting, the user again receives the same custom post.

**Steps to reproduce:**
1. Start a new meeting from desired user's account.
2. Without ending the meeting started, try to start a new meeting again.
3. Click on Create new meeting.

The user is presented with multiple similar posts to create a new meeting.

image

### PR DESCRIPTION
**Pull request by raghavaggarwal2308**
#### Summary
Fix the following issues:
- Not able to create a meeting in the threads view.
- Not able to create a meeting by clicking "Create New Meeting" in a channel.

#### What to test?
- Able to create a meeting in the threads view
- Able to create a new meeting by clicking the "Create New Meeting" button

###### Steps to reproduce:
- For threads view:
1. Have CRT enabled, and open the Threads view
2. Open a thread that pops into the RHS
3. Click the Zoom button on the right

- For clicking the button:
1. Start a new meeting from the desired user's account.
2. Without ending the meeting started, try to start a new meeting again.
3. Click on the "Create New Meeting" button.

###### Expected behaviour:
- The meetings should be created successfully.

###### Environment:
MM version: v7.8.10
Node version: 14.18.0
Go version: 1.19.0

#### Ticket Link

FIxes #311

### CODE REVIEW

**Comment by mickmister** [comment]
@raghavaggarwal2308 Did you check the box that allows maintainers to edit the PR?

File: webapp/src/actions/index.js [hunk 1]
```diff
@@ -5,19 +5,11 @@ import {PostTypes} from 'mattermost-redux/action_types';
...
-                meetingURL = await Client.forceStartMeeting(
-                    channelId, true, '', 0, topic,
-                );
-            } else {
-                meetingURL = await Client.startMeeting(
-                    channelId, true, '', 0, false, topic,
-                );
-            }
+            const startFunction = force ? Client.forceStartMeeting : Client.startMeeting;
+            const meetingURL = await startFunction(channelId, rootId, true, topic);
```
Comment (mickmister) [inline webapp/src/actions/index.js:12]: Looks good for this PR. Unrelated comment below

---

Do we really need a `Client.forceStartMeeting`? Since that function really just calls `Client.startMeeting` with `force=true`

Also, this function signature is pretty hard to read, along with the function call below. Thoughts on changing this to accept an object instead? Would be best if it were typescript as well so we have type safety on the object

```ts
type StartMeetingArgs = {
    channelId: string;
    rootId?: string;
    force?: boolean;
    topic?: string;
}

export function startMeeting(args: StartMeetingArgs) {
    return async (dispatch, getState) => {
        try {
            const startFunction = force ? Client.forceStartMeeting : Client.startMeeting;
            const meetingURL = await startFunction(channelId, rootId, true, topic);
```

We can do this as a follow up thing since that would expand the scope of this fix quite a bit

File: webapp/src/client/client.js [hunk 2]
```diff
@@ -11,14 +11,13 @@ export default class Client {
         this.url = url + '/plugins/' + id;
     }
 
-    startMeeting = async (
-        channelId, personal = true, topic = '', meetingId = 0, force = false,
-    ) => {
+    startMeeting = async (channelId, rootId, personal = true, topic = '', meetingId = 0, force = false) => {
```
Comment (mickmister) [inline webapp/src/client/client.js:14]: Is `meetingId` ever defined when calling these client functions?

**Review by mickmister — APPROVED** [review]
The code is a bit hard to read/understand (not the changes in this PR, just the code itself). I suggest as a follow up we introduce typescript into this repo and use objects as the function args for `startMeeting` etc.

For the purpose of this fix, LGTM :+1:

File: webapp/src/client/client.js (hunk 2 above)
Comment (raghavaggarwal2308) [reply webapp/src/client/client.js:14]: @mickmister I don't think this will ever be defined.

File: webapp/src/actions/index.js (hunk 1 above)
Comment (raghavaggarwal2308) [reply webapp/src/actions/index.js:12]: @mickmister I agree with your suggestions. Should I create an issue for the same?

File: webapp/src/client/client.js (hunk 2 above)
Comment (mickmister) [reply webapp/src/client/client.js:14]: @raghavaggarwal2308 If it's never defined when this function is called anywhere in the plugin, then I think we should remove the function parameter in this PR. Do you think it will eventually be used?

File: webapp/src/actions/index.js (hunk 1 above)
Comment (mickmister) [reply webapp/src/actions/index.js:12]: @raghavaggarwal2308 Yes sounds good to me :+1:

File: webapp/src/client/client.js (hunk 2 above)
Comment (raghavaggarwal2308) [reply webapp/src/client/client.js]: @mickmister I don't think it will be used. Removed it now.

File: webapp/src/actions/index.js (hunk 1 above)
Comment (raghavaggarwal2308) [reply webapp/src/actions/index.js]: @mickmister Created the issue. Please let me know if we need to add anything else.
https://github.com/mattermost/mattermost-plugin-zoom/issues/319

File: webapp/src/client/client.js [hunk 3]
```diff
@@ -11,22 +11,16 @@ export default class Client {
         this.url = url + '/plugins/' + id;
     }
 
-    startMeeting = async (channelId, rootId, personal = true, topic = '', meetingId = 0, force = false) => {
+    startMeeting = async (channelId, rootId, personal = true, topic = '', force = false) => {
```
Comment (mickmister) [inline webapp/src/client/client.js:14]: Seems like `personal` is always `true` as well right? I think these were added as placeholders, but they haven't been implemented for years so I think they are a bit of tech debt at this point. Do you see value in keeping it around? I don't want to add risk to the PR so I trust your judgment

Comment (raghavaggarwal2308) [reply webapp/src/client/client.js]: @mickmister I don't think we need this for now. I have removed it. We can always add it back if we need it in the future.

**Review by AayushChaudhary0001 — APPROVED** [review]
Tested and approved.

This PR is tested for the below scenarios :-

- Able to create a meeting having CRT enabled in threads view.
- Able to start a new meeting by clicking the "Create new meeting" button.

Working fine, LGTM.
