### PR TITLE
Fix meeting ended webhook

### LINKED ISSUE #72: Webhooks not updating meeting info box
Plugin version: 1.3
Mattermost version: 5.20.1

Related to:
https://github.com/mattermost/mattermost-plugin-zoom/issues/37

At present, the plugin does not seem to update meeting info boxes in response to webhook calls by Zoom. I can confirm that the webhook calls are being made by Zoom because the request is being received reliably by a webhook testing URL. I can also confirm that the webhook address entered in the jwt app configuration is correctly configured with the appropriate secret because that URL returns an empty response when requested in curl.

Any thoughts or suggestions? I'm happy to do more debugging, but I don't know quite where to start.

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

Zoom seems to have completely changed their webhook payloads to be `application/json` instead of `application/x-www-form-urlencoded`. https://marketplace.zoom.us/docs/api-reference/webhook-reference#notification-structure

This PR fixes this on our end by supporting the new payload format.

#### Ticket Link

Fixes #72
https://mattermost.atlassian.net/browse/MM-20656

### CODE REVIEW

File: server/http.go [hunk 1]
```diff
@@ -42,42 +42,55 @@ func (p *Plugin) handleWebhook(w http.ResponseWriter, r *http.Request) {
...
 		http.Error(w, err.Error(), http.StatusBadRequest)
 		return
 	}
 
-	p.handleStandardWebhook(w, r, &webhook)
+	if webhook.Event == zoom.EventTypeMeetingEnded {
+		var meetingWebhook zoom.MeetingWebhook
+		err = json.Unmarshal(b, &meetingWebhook)
+		if err != nil {
+			http.Error(w, err.Error(), http.StatusBadRequest)
```
Comment (hanzei) [inline server/http.go:68]: Same here

File: server/http.go [hunk 2]
```diff
@@ -87,17 +100,21 @@ func (p *Plugin) handleStandardWebhook(w http.ResponseWriter, r *http.Request, w
...
 
-	if appErr := p.API.KVDelete(key); appErr != nil {
+	appErr = p.API.KVDelete(key)
+	if appErr != nil {
 		p.API.LogWarn("failed to delete db entry", "error", appErr.Error())
 		return
 	}
 
-	if _, err := w.Write([]byte(post.ToJson())); err != nil {
+	w.WriteHeader(http.StatusOK)
```
Comment (hanzei) [inline server/http.go:115]: Is this needed?

File: server/http.go [hunk 3]
```diff
@@ -87,17 +100,21 @@ func (p *Plugin) handleStandardWebhook(w http.ResponseWriter, r *http.Request, w
 	post.Message = "Meeting has ended."
 	post.Props["meeting_status"] = zoom.WebhookStatusEnded
 
-	if _, appErr := p.API.UpdatePost(post); appErr != nil {
+	_, appErr = p.API.UpdatePost(post)
+	if appErr != nil {
```
Comment (hanzei) [inline server/http.go:104]: I'm not sure if this makes the code more readable. What is your reasoning behind the change?

File: server/http.go [hunk 4]
```diff
@@ -151,20 +169,23 @@ func (p *Plugin) handleStartMeeting(w http.ResponseWriter, r *http.Request) {
...
-	if _, appErr = p.API.GetChannelMember(req.ChannelID, userID); appErr != nil {
+	_, appErr = p.API.GetChannelMember(req.ChannelID, userID)
+	if appErr != nil {
 		http.Error(w, "Forbidden", http.StatusForbidden)
 		return
 	}
 
-	if forceCreate := r.URL.Query().Get("force"); forceCreate == "" {
+	forceCreate := r.URL.Query().Get("force")
+	if forceCreate == "" {
```
Comment (hanzei) [inline server/http.go:179]: Nit:
```suggestion
	if r.URL.Query().Get("force") == "" {
```

File: server/http.go [hunk 5]
```diff
@@ -42,42 +42,55 @@ func (p *Plugin) handleWebhook(w http.ResponseWriter, r *http.Request) {
...
-	}
+	w.WriteHeader(http.StatusNotImplemented)
+}
 
-	key := fmt.Sprintf("%v%v", postMeetingKey, webhook.ID)
+func (p *Plugin) handleMeetingEnded(w http.ResponseWriter, r *http.Request, webhook *zoom.MeetingWebhook) {
+	key := fmt.Sprintf("%v%v", postMeetingKey, webhook.Payload.Object.ID)
 	b, appErr := p.API.KVGet(key)
-	if appErr != nil {
+	if appErr != nil && !strings.Contains(appErr.Error(), "not found") {
```
[the remark this answers is not in the document]
Comment (mickmister) [reply server/http.go:83]: I'll look into this. It is a pattern we have in mscalendar, but it may be custom functionality bubbled up from the store layer there.

File: server/http.go (hunk 2 above)
Comment (mickmister) [reply server/http.go:115]: It's not necessary. Thank you for your explanation https://github.com/mattermost/mattermost-plugin-github/pull/239#discussion_r422431624

File: server/http.go (hunk 3 above)
Comment (mickmister) [reply server/http.go:104]: It is personally easier for me to scan/read, but I understand if it is not for others. I assume it is common in the Go community to use the `if ...;` syntax. Though using separate lines is a convention the integrations team has made for any new code we introduce across the plugins we maintain.

Comment (mickmister) [reply server/http.go:104]: How strongly do you feel about changing the blocks back to the `if ...;` syntax?

**Comment by mickmister** [comment]
@hanzei 
> I'm quite surprised that Zoom breaks there API like this.

I am very shocked too. I don't see anything in their documentation about the change nor do I see anything in the docs about the old implementation. It's very strange. Here's a changelog where I would expect to see this info outlined https://support.zoom.us/hc/en-us/articles/204758419-New-updates-for-Web

I did not previously have a webhook setup for testing, so I had to set one up for this task. I'm wondering if someone from the team that does can verify that pre-existing webhook setups have had their payload structure changed. I posted in the Zoom channel to ask for help on this.

> Is there any legacy mode? Or a mailing list to get this changes early?

I'm not seeing anything about the change, so I don't think they have any docs on the legacy setup. However, it could be on their site somewhere I haven't found.

There is a `Follow` button on the main release notes page to subscribe to updates. I assume this is for subscribing via email, but it does not make it clear what the `Follow` feature entails.
https://support.zoom.us/hc/en-us/sections/201214205-Release-Notes

File: server/http.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (hanzei) [reply server/http.go:83]: From looking at the test cases in `mattermost-server`, `KVGet` returns `(nil, nil)` is no value is found.

File: server/http.go (hunk 3 above)
Comment (hanzei) [reply server/http.go:104]: Good question. 0/5, it's personal preference.

**Comment by hanzei** [comment]
Does the [WaybackMachine](https://web.archive.org/) report any changes on the documentation page in the last few month?

**Comment by mickmister** [comment]
@hanzei There doesn't seem to be any relevant info on docs changes from my search on the WaybackMachine.

I see that one of the archive snapshots was triggered by `outlinks-from-tweets`. I'm not sure if this means people were linking to the zoom site in general, or specifically to the docs page. Searching for tweets around that time, I'm not finding anyone linking to the docs on twitter. I would expect to see someone complaining to zoom about the sudden change, if it was triggered by a link to the docs.

image

File: server/http.go [hunk 6]
```diff
@@ -42,42 +42,56 @@ func (p *Plugin) handleWebhook(w http.ResponseWriter, r *http.Request) {
...
+	if err != nil {
+		p.API.LogError("Error unmarshaling webhook", "err", err.Error())
+		http.Error(w, err.Error(), http.StatusBadRequest)
+		return
+	}
 
-	// TODO: handle recording webhook
-}
+	if webhook.Event != zoom.EventTypeMeetingEnded {
+		// TODO: handle recording webhook
```
Comment (hanzei) [inline server/http.go:66]: Maybe open a ticket for meeting recording and remove the comment?

Comment (mickmister) [reply server/http.go]: https://github.com/mattermost/mattermost-plugin-zoom/issues/110 comment removed :+1:

**Comment by DHaussermann** [comment]
@mickmister I set this up locally and I'm not seeing this work. My zoom post does not get updated via the subscription when the meeting ends. 
- The Zoom app otherwise works
- Double checked URL and secret in the `Event notification endpoint URL` fileld
- As per documentation `End Meeting` is the selected event.
- On my ngrok tunnel I can see `POST /plugins/zoom/webhook      400 Bad Request` put don't know what's in the payload


Any thoughts? 
Also in case it's relevant, I notice that Zoom app provides a `Verification Token` but there is nowhere to set it in Mattermost plugin UI.
ZoomToken

**Comment by larkox** [comment]
Looking at the code, @mickmister is not using the verification token. Actually, as far as I have checked, the authorization token is only provided for published apps in the marketplace, so I would say the best would be to just use the Webhook secret, since it does a similar function.

Regarding why this may not be working, I have no idea. Everything looks fine in the code. I will let @mickmister answer that part.

**Comment by mickmister** [comment]
Quote from one of my comments above:

> I did not previously have a webhook setup for testing, so I had to set one up for this task. I'm wondering if someone from the team that does can verify that pre-existing webhook setups have had their payload structure changed.

@DHaussermann Did you already have the webhooks set up in Zoom? 

To view the body of a request in the ngrok interface, select the request on hte left side, then use the right side of the page to view the body. You can use the `Raw` tab to view the entire request. Here's an example of viewing a request:

image
