### PR TITLE
Fix issue of zoom settings command being ignored after connecting user

### LINKED ISSUE #345: User not getting option to select meeting ID type
#### Summary
- Case: A not-connected user tries to create a meeting and the PMI setting is set to "ask"
    - In the above case the user gets a link to connect their account and once the account is connected the meeting is created by a unique meeting ID.
   
#### Expected
- The user should get an option to select a meeting ID type before the meeting is created.

#### Steps to reproduce
1. Disconnect your Zoom account
2. Create a meeting using the slash command or zoom app bar icon.

#### Screenshot
image

### PR DESCRIPTION
**Pull request by ayusht2810**
#### Summary
- Fixed issue of zoom settings command being ignored after connecting user

#### Ticket Link
Fixes #345 

#### What to test?
- Zoom Settings are being checked after connecting of the user

#### Checklist
- [x] Completed dev testing
- [x] `make test` Ran test cases and ensured they are passing
- [x] `make check-style` Ran style check and ensured both webapp and server pass the checks

#### Demo
[screen-capture (9).webm](https://github.com/mattermost/mattermost-plugin-zoom/assets/100013900/c5f40e9f-92f4-478c-b279-17632de7464c)

### CODE REVIEW

File: server/http.go [hunk 1]
```diff
@@ -358,18 +358,49 @@ func (p *Plugin) completeUserOAuthToZoom(w http.ResponseWriter, r *http.Request)
...
-		meetingID := meeting.ID
-		if err = p.postMeeting(user, meetingID, channelID, "", ""); err != nil {
-			p.API.LogWarn("Failed to post the meeting", "error", err.Error())
-			http.Error(w, err.Error(), http.StatusInternalServerError)
-			return
+		createMeetingWithPMI := false
+		createMeetingWithPref := false
+		switch userPMISettingPref {
+		case "", zoomPMISettingValueAsk:
+			p.askPreferenceForMeeting(user.Id, channelID, "")
```
Comment (mickmister) [inline server/http.go:373]: Is this logic used somewhere else? Is there an opportunity to de-duplicate code into a shared function?

File: server/http.go [hunk 2]
```diff
@@ -358,18 +358,49 @@ func (p *Plugin) completeUserOAuthToZoom(w http.ResponseWriter, r *http.Request)
...
 		}
 
-		meetingID := meeting.ID
-		if err = p.postMeeting(user, meetingID, channelID, "", ""); err != nil {
-			p.API.LogWarn("Failed to post the meeting", "error", err.Error())
-			http.Error(w, err.Error(), http.StatusInternalServerError)
-			return
+		createMeetingWithPMI := false
+		createMeetingWithPref := false
+		switch userPMISettingPref {
```
Comment (raghavaggarwal2308) [inline server/http.go:371]: The code below code is same as the code present in `handleStartMeeting` function. I think we should create a common function for this.

File: server/http.go [hunk 3]
```diff
@@ -358,18 +358,49 @@ func (p *Plugin) completeUserOAuthToZoom(w http.ResponseWriter, r *http.Request)
...
+			}
+		default:
+			meetingID, createMeetingErr = p.createMeetingWithoutPMI(user, zoomUser, channelID, defaultMeetingTopic)
+			if createMeetingErr != nil {
+				p.API.LogWarn("Error creating the meeting", "Error", createMeetingErr.Error())
+				return
+			}
+		}
+
+		if !createMeetingWithPref {
```
Comment (raghavaggarwal2308) [inline server/http.go:395]: I do no think we need this conditional. It will not post a meeting in the channel in case of PMI setting true

**Review by raghavaggarwal2308 — CHANGES_REQUESTED** [review]

File: server/http.go (hunk 3 above)
Comment (ayusht2810) [reply server/http.go]: We need this condition to complete the oauth so that the oauth tab also closes or shows a successfully connected state. On removing this, the user gets connected, but the tab doesn't close.

**Comment by ayusht2810** [comment]
@mickmister @raghavaggarwal2308 fixed the review fixes. Please re-review

File: server/telemetry.go [hunk 4]
```diff
@@ -4,7 +4,6 @@ const (
 	telemetryOauthModeOauth             = "Oauth"
 	telemetryOauthModeOauthAccountLevel = "Oauth Account Level"
 
-	telemetryStartSourceWebapp  = "webapp"
```
Comment (raghavaggarwal2308) [inline server/telemetry.go:7]: Why is this removed?

File: server/http.go [hunk 5]
```diff
@@ -581,54 +572,15 @@ func (p *Plugin) handleStartMeeting(w http.ResponseWriter, r *http.Request) {
...
-		if createMeetingErr != nil {
-			p.API.LogWarn("failed to create the meeting", "Error", createMeetingErr.Error())
-			http.Error(w, createMeetingErr.Error(), http.StatusInternalServerError)
-			return
-		}
 	}
 
-	if err = p.postMeeting(user, meetingID, req.ChannelID, req.RootID, topic); err != nil {
-		http.Error(w, err.Error(), http.StatusInternalServerError)
+	if meetingID == 0 {
```
Comment (raghavaggarwal2308) [inline server/http.go:580]: Can we return the meeting URL from the function instead of ID. In that case we will not have to add this conditional and we will not need to pass the io.writer to `handleMeetingCreation`

**Review by raghavaggarwal2308 — CHANGES_REQUESTED** [review]

File: server/http.go (hunk 3 above)
Comment (raghavaggarwal2308) [reply server/http.go]: @ayusht2810 I don't think these two things are related. Please verify

File: server/telemetry.go (hunk 4 above)
Comment (ayusht2810) [reply server/telemetry.go:7]: This was not used anywhere and was giving linting error

**Review by raghavaggarwal2308 — APPROVED** [review]

File: server/http.go [hunk 6]
```diff
@@ -354,22 +354,12 @@ func (p *Plugin) completeUserOAuthToZoom(w http.ResponseWriter, r *http.Request)
...
-			return
-		}
-
-		meetingID := meeting.ID
-		if err = p.postMeeting(user, meetingID, channelID, "", ""); err != nil {
-			p.API.LogWarn("Failed to post the meeting", "error", err.Error())
-			http.Error(w, err.Error(), http.StatusInternalServerError)
-			return
-		}
+		// Ignoring the returned error here as we are already logging it in the function.
```
Comment (mickmister) [inline server/http.go:360]: Can we instead log the error here? This sort of comment seems a little out of place

**Review by mickmister — APPROVED** [review]

**Comment by ayusht2810** [comment]
@mickmister fixed the review comment. Please re-review

File: server/http.go [hunk 7]
```diff
@@ -867,7 +869,6 @@ func (p *Plugin) handleMeetingCreation(channelID, rootID, topic string, user *mo
 	var createMeetingErr error
 	userPMISettingPref, err := p.getPMISettingData(user.Id)
 	if err != nil {
-		p.API.LogWarn("Error fetching PMI setting data", "Error", err.Error())
 		return "", err
```
Comment (mickmister) [inline server/http.go:872]: Ideally we retain the context that we had error as well

```go
return "", errors.Wrap(err, "Error fetching PMI setting data")
```

File: server/http.go [hunk 8]
```diff
@@ -357,9 +357,10 @@ func (p *Plugin) completeUserOAuthToZoom(w http.ResponseWriter, r *http.Request)
 	if justConnect {
 		p.postEphemeral(userID, channelID, "", "Successfully connected to Zoom")
 	} else {
-		// Ignoring the returned error here as we are already logging it in the function.
 		// Returning error might not be true here as the main logic for this API is to connect users.
```
Comment (mickmister) [inline server/http.go:360]:
```suggestion
		// Returning error might not be appropriate here as the main logic for this API is to connect users.
```

**Comment by raghavaggarwal2308** [comment]
@mickmister Fixed the review comments added by you

**Comment by mickmister** [comment]
@ayusht2810 Does this need QA review or do you think this is good to merge?

**Review by mickmister — APPROVED** [review]

**Comment by ayusht2810** [comment]
@mickmister The PR is ready for merge but it can't be merged now as @wiggin77 review is still pending as code owner. Meanwhile, @AayushChaudhary0001 can also give the PR a quick test, if he wants to.

**Review by AayushChaudhary0001 — APPROVED** [review]
The above PR has been tested for the following scenarios:

- Tested the Zoom Settings command after connecting of the user
- Tested the Zoom Settings command after disconnecting of the user

The PR was working fine for both the conditions, LGTM. Approved

File: server/http.go [hunk 9]
```diff
@@ -915,3 +863,45 @@ func (p *Plugin) slackAttachmentToUpdatePMI(currentValue, channelID string) *mod
 
 	return &slackAttachment
 }
+
+func (p *Plugin) handleMeetingCreation(channelID, rootID, topic string, user *model.User, zoomUser *zoom.User) (string, error) {
+	var meetingID int
+	var createMeetingErr error
+	userPMISettingPref, err := p.getPMISettingData(user.Id)
+	if err != nil {
+		return "", errors.Wrap(err, "Error fetching PMI setting data")
```
Comment (wiggin77) [inline server/http.go:872]:
```suggestion
		return "", errors.Wrap(err, "error fetching PMI setting data")
```

See https://google.github.io/styleguide/go/decisions.html#error-strings
