### PR TITLE
[MI-3765] Fix issue: "Create New Meeting" button not working in threads view

### LINKED ISSUE #317: Not able to create new meeting in the threads view after clicking "Create New Meeting" button
#### Summary
Not able to create a new meeting in the threads view after clicking the "Create New Meeting" button.

#### Steps to reproduce:
1. Have CRT (Collapsed Reply Threads) enabled, and open the Threads view.
2. Open a thread that pops into the RHS.
3. Start a new meeting by clicking the Zoom button on the right.
2. Without ending the meeting started, try to start a new meeting again.
3. Click on the "Create New Meeting" button.

#### Expected behavior:
- The user should be able to start a new meeting.

#### Current behaviour:
- No new meeting is posted inside the channel.

### PR DESCRIPTION
**Pull request by raghavaggarwal2308**
#### Summary
In the threads view on MM, when we were clicking the "Create New Meeting" button, no new meeting was getting created because of missing "RootID" while calling the "startMetting" function. We fixed the issue the sending the root ID present in the props.

#### What to test?
- The "Create New Meeting" button is creating a new meeting in the threads view.

###### Steps to reproduce:
1. Connect your Zoom account.
2. Have CRT (Collapsed Reply Threads) enabled, and open the Threads view.
3. Open a thread that pops into the RHS.
4. Start a new meeting by clicking the Zoom button on the right.
5. Without ending the meeting started, try to start a new meeting again.
6. Click on the "Create New Meeting" button.

###### Expected behavior:
- A new meeting is posted inside the thread.

###### Environment:
MM version: v9.2.2
Node version: 14.18.0
Go version: 1.20.11

#### Ticket Link
Fixes #317

### CODE REVIEW

**Review by mickmister — APPROVED** [review]

File: webapp/src/components/post_type_zoom/post_type_zoom.jsx [hunk 1]
```diff
@@ -177,7 +177,7 @@ export default class PostTypeZoom extends React.PureComponent {
                         className='btn btn-lg btn-primary'
                         style={style.button}
                         rel='noopener noreferrer'
-                        onClick={() => this.props.actions.startMeeting(this.props.currentChannelId, '', true, props.meeting_topic)}
+                        onClick={() => this.props.actions.startMeeting(post.channel_id, post.root_id, true, props.meeting_topic)}
```
Comment (mickmister) [inline webapp/src/components/post_type_zoom/post_type_zoom.jsx:180]: Not sure if this applies here, but whenever we reference `post.root_id`, we usually have a `|| post.id` to say "and also handle this if the post is itself a root post"

```suggestion
                        onClick={() => this.props.actions.startMeeting(post.channel_id, post.root_id || post.id, true, props.meeting_topic)}
```

Comment (mickmister) [reply webapp/src/components/post_type_zoom/post_type_zoom.jsx:180]: Just to make sure, there is never any benefit to using `post.id` here

Comment (raghavaggarwal2308) [reply webapp/src/components/post_type_zoom/post_type_zoom.jsx:180]: @mickmister Yes, it won't be useful
