### PR TITLE
[GH-313] Redirect user when a new meeting is started

### LINKED ISSUE #313: User not getting redirected to a new tab
When a user clicks on the Zoom icon in the header or app bar, they should be redirected to a new tab.

**Steps to reproduce:**
1. Click on the Zoom button.

The user should be redirected to a new tab, but they are not getting re-directed.

### PR DESCRIPTION
**Pull request by raghavaggarwal2308**
#### Summary
- When a new meeting is started using the Zoom icon in the app bar/channel header the user is not getting redirected to the meeting tab because the meeting URL is undefined.
- We updated the logic to convert the response of the start meeting API to JSON for fetching the meeting URL.

#### What to test?
- When a user starts a new meeting using the Zoom icon in the app bar/channel header, he/she should be redirected to the meeting page.

###### Steps to reproduce:
- Click on the Zoom icon in the app bar/channel header. (Note: These should not be an existing meeting of the user in that channel)

###### Environment:
MM version: v7.8.10
Node version: 14.18.0
Go version: 1.19.0

#### Ticket Link

Fixes #313

### CODE REVIEW

File: webapp/src/client/client.js [hunk 1]
```diff
@@ -20,7 +20,9 @@ export default class Client {
             topic,
             meeting_id: meetingId,
         });
-        return res.meeting_url;
+
+        const data = await res.json();
+        return data.meeting_url;
```
Comment (mickmister) [inline webapp/src/client/client.js:25]: I think the bug here is actually in `doPost`. We should be returning `response.json()` instead of just `response` in `doPost`

Comment (raghavaggarwal2308) [reply webapp/src/client/client.js]: @mickmister Fixed

**Review by mickmister — APPROVED** [review]

**Review by AayushChaudhary0001 — APPROVED** [review]
Tested and approved
Working fine, LGTM
